[project]
name = "simple-multimodal-rag-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.53.0",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
]
