# Open WebUI Pipeline Configuration for Multimodal RAG

# Model Configuration
model:
  text_generation: "llama3.2"  # Ollama model used by Open WebUI
  embeddings: "text-embedding-3-small"  # OpenAI embeddings model
  tokenizer: "sentence-transformers/all-MiniLM-L6-v2"

# Document Processing Configuration
document:
  image_resolution_scale: 2
  max_tokens: 512
  doc_dir: "documents"
  supported_file_types: [".pdf"]
  picture_description:
    prompt_picture_description: "Describe this image in sentences in a single paragraph."

# Vector Database Configuration
database:
  uri: "http://localhost:19530"
  name: "rag_multimodal"
  collection_name: "rag_collection"
  namespace: "OpenWebUI"

# Open WebUI Specific Configuration
openwebui:
  pipeline_name: "Multimodal RAG Pipeline"
  max_search_results: 5
  similarity_threshold: 0.3
  enable_document_upload: true
  enable_stats_command: true
  enable_help_command: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"