name: PR Tests

on:
    pull_request:
        branches: [main, develop]
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    pr-tests:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout PR code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Set up Python 3.12
              run: uv python install 3.12

            - name: Install dependencies
              run: uv sync

            - name: Run fast tests only
              run: |
                  # Run only unit tests, skip integration tests
                  uv run pytest test/ -v -m "not integration" --tb=short

            - name: Comment PR with test results
              uses: actions/github-script@v7
              if: always()
              with:
                  script: |
                      const fs = require('fs');
                      const testStatus = '${{ job.status }}';
                      const body = testStatus === 'success' 
                        ? '✅ All tests passed! This PR is ready for review.'
                        : '❌ Some tests failed. Please check the test results and fix any issues.';

                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: body
                      });
