name: Test Suite

on:
    push:
        branches: [main, develop, openwebui]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Set up Python 3.12
              run: uv python install 3.12

            - name: Install dependencies
              run: uv sync

            - name: Run pytest
              run: uv run pytest test/ -v

            - name: Generate test report
              if: always()
              run: |
                  uv run pytest test/ -v --tb=short --junit-xml=test-results.xml

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results
                  path: test-results.xml
